"""
VNS Fair VRP Solver
"""
from __future__ import annotations
import collections.abc
import typing
__all__: list[str] = ['AgentSolution', 'AnnealingSolver', 'BaselineSolver', 'BenchmarkMetadata', 'InputData', 'RebalancingSolver', 'Solution', 'Solver']
class AgentSolution:
    def __init__(self) -> None:
        ...
    @property
    def route(self) -> list[int]:
        ...
    @property
    def solution_size(self) -> int:
        ...
    @property
    def total_distance(self) -> int:
        ...
    @property
    def total_time(self) -> int:
        ...
    @property
    def total_value(self) -> int:
        ...
class AnnealingSolver(Solver):
    def __init__(self, st: typing.SupportsFloat | typing.SupportsIndex, aon: typing.SupportsInt | typing.SupportsIndex, max_iter: typing.SupportsInt | typing.SupportsIndex, time_limit: typing.SupportsInt | typing.SupportsIndex, alpha: typing.SupportsFloat | typing.SupportsIndex = 0.5) -> None:
        ...
    def solve(self, instance: InputData) -> Solution:
        ...
class BaselineSolver(Solver):
    def __init__(self, st: typing.SupportsFloat | typing.SupportsIndex, aon: typing.SupportsInt | typing.SupportsIndex, max_iter: typing.SupportsInt | typing.SupportsIndex, time_limit: typing.SupportsInt | typing.SupportsIndex) -> None:
        ...
    def solve(self, instance: InputData) -> Solution:
        ...
class BenchmarkMetadata:
    def __init__(self) -> None:
        ...
    @property
    def alpha(self) -> float:
        ...
    @property
    def aon(self) -> int:
        ...
    @property
    def execution_time(self) -> float:
        ...
    @property
    def fairness(self) -> float:
        ...
    @property
    def max_iter(self) -> int:
        ...
    @property
    def st(self) -> float:
        ...
    @property
    def time_limit(self) -> int:
        ...
class InputData:
    def __init__(self, points_count: typing.SupportsInt | typing.SupportsIndex, min_load: typing.SupportsInt | typing.SupportsIndex, max_load: typing.SupportsInt | typing.SupportsIndex, max_time: typing.SupportsInt | typing.SupportsIndex, max_distance: typing.SupportsInt | typing.SupportsIndex, distance_matrix: collections.abc.Sequence[collections.abc.Sequence[typing.SupportsInt | typing.SupportsIndex]], time_matrix: collections.abc.Sequence[collections.abc.Sequence[collections.abc.Sequence[typing.SupportsInt | typing.SupportsIndex]]], point_scores: collections.abc.Sequence[typing.SupportsInt | typing.SupportsIndex], point_service_times: collections.abc.Sequence[typing.SupportsInt | typing.SupportsIndex]) -> None:
        ...
    def get_time_dependent_cost(self, time: typing.SupportsInt | typing.SupportsIndex, start: typing.SupportsInt | typing.SupportsIndex, finish: typing.SupportsInt | typing.SupportsIndex) -> int:
        ...
    @property
    def distance_matrix(self) -> list[list[int]]:
        ...
    @distance_matrix.setter
    def distance_matrix(self, arg0: collections.abc.Sequence[collections.abc.Sequence[typing.SupportsInt | typing.SupportsIndex]]) -> None:
        ...
    @property
    def max_distance(self) -> int:
        ...
    @max_distance.setter
    def max_distance(self, arg0: typing.SupportsInt | typing.SupportsIndex) -> None:
        ...
    @property
    def max_load(self) -> int:
        ...
    @max_load.setter
    def max_load(self, arg0: typing.SupportsInt | typing.SupportsIndex) -> None:
        ...
    @property
    def max_time(self) -> int:
        ...
    @max_time.setter
    def max_time(self, arg0: typing.SupportsInt | typing.SupportsIndex) -> None:
        ...
    @property
    def min_load(self) -> int:
        ...
    @min_load.setter
    def min_load(self, arg0: typing.SupportsInt | typing.SupportsIndex) -> None:
        ...
    @property
    def point_scores(self) -> list[int]:
        ...
    @point_scores.setter
    def point_scores(self, arg0: collections.abc.Sequence[typing.SupportsInt | typing.SupportsIndex]) -> None:
        ...
    @property
    def point_service_times(self) -> list[int]:
        ...
    @point_service_times.setter
    def point_service_times(self, arg0: collections.abc.Sequence[typing.SupportsInt | typing.SupportsIndex]) -> None:
        ...
    @property
    def points_count(self) -> int:
        ...
    @points_count.setter
    def points_count(self, arg0: typing.SupportsInt | typing.SupportsIndex) -> None:
        ...
    @property
    def time_matrix(self) -> list[list[list[int]]]:
        ...
    @time_matrix.setter
    def time_matrix(self, arg0: collections.abc.Sequence[collections.abc.Sequence[collections.abc.Sequence[typing.SupportsInt | typing.SupportsIndex]]]) -> None:
        ...
class RebalancingSolver(Solver):
    def __init__(self, st: typing.SupportsFloat | typing.SupportsIndex, aon: typing.SupportsInt | typing.SupportsIndex, max_iter: typing.SupportsInt | typing.SupportsIndex, time_limit: typing.SupportsInt | typing.SupportsIndex, fairness: typing.SupportsFloat | typing.SupportsIndex) -> None:
        ...
    def solve(self, instance: InputData) -> Solution:
        ...
class Solution:
    def __init__(self) -> None:
        ...
    @property
    def agents(self) -> list[AgentSolution]:
        ...
    @property
    def meta(self) -> BenchmarkMetadata:
        ...
class Solver:
    def solve(self, instance: InputData) -> Solution:
        ...
